    - name: install a configure web server
      hosts: all
      become: yes
      tasks:
    - name: install nginx web server
      package: 
        name: nginx 
        state: present
    - name: find all the default files
      find:
        paths: /usr/share/nginx/html/
        file_type: any
      register: OUT
    - name: delete the files
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{OUT.files}}"
      become: yes
      
    - name: download student app content
      unarchive:
        src: https://studentapi-cit.s3-us-west-2.amazonaws.com/studentapp-frontend.tar.gz
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: start the service
      service:
        name: nginx
        state: restarted
        enabled: yes