- name: find the list of files in a directory
  hosts: all
  tasks:
    - name: find all the lines
      find:
        paths: /usr/share/nginx/html/
        file_type: any
      register: OUT
  
  - name: delete the files
    file:
      path: "{{item.path}}"
      state: absent
    loop: "{{OUT.files}}"
        