- name: update a file with lineinfile
  hosts: all
  tasks:
    - name: update nginx conf file
      lineinfile:
       path: /tmp/nginx.conf
       insertbefore: "^        error_page 404 /404.html;"
       line: "\tlocation /student {\n\t\tproxy_pass http://localhost:8080/student;\n\t}"