### Declare a variable  at play and print the value.

- name: Print a variable from play
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable 
      debug:
        msg: "URL = {{URL}}"

### Declare a variable at task and print the value.

- name: Print a variable from task
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable 
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com 

## What happens if you have same variable in both PLAY and TASK  ??
## Local variables are prioritized in any scripting language , So task variable is going to be the value parsed to task. And always you get vars from task 

## Variable data can be loaded from variable file 

- name: Print values from a file 
  hosts: all 
  vars_files:
    - file.yml
  tasks:
    - name: Print a value from Vars File 
      debug:
        msg: URL = {{URL}}

# Which variable will be picked up if you have given both VARS_FILES and then VARS ??
## VARS get more priority than VARS_FILES.


## Variable data can be read from USER as well like read command in shell scripting.

- name: Print values from a file 
  hosts: all 
  vars_prompt:
    - name: URL 
      prompt: Enter the URL
      private: no
  tasks:
    - name: Print a value from prompt File 
      debug:
        msg: URL = {{URL}} 


## Variable can be read from inventory file as well 
# IP  URL_HOST=host.google.com 

- name: Print values from a invetnory file 
  hosts: all 
  tasks:
    - name: Print a value from inventory File 
      debug:
        msg: URL = {{URL_HOST}} 


## Access varibles from facts. 

- name: Access facts.
  hosts: all
  tasks:
    - name: Print total mem of node.
      debug:
        msg: Total Mem = {{facter_memorysize_mb}}
