- name: Install Java 
  package:
    name: java 
    state: latest 
  notify: Restart Tomcat 
  
- name: Create Application User 
  user:
    name: "{{APPUSER}}"

- name: Check a tomcat directory exists or not 
  stat:
    path: /home/student/apache-tomcat-{{TOMCAT_VERSION}}
  register: tomcat_dir_check

- name: Download Tomcat 
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "/home/{{APPUSER}}"
    remote_src: yes
  become_user: "{{APPUSER}}"
  when: tomcat_dir_check.stat.exists|bool == false
  notify: Restart Tomcat 

- name: Download StudentApp War file 
  get_url:
    url: "{{WAR_URL}}"
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/webapps"
  become_user: "{{APPUSER}}"

- name: Download JDBC Jar file 
  get_url:
    url: "{{JDBC_URL}}"
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/lib"
  become_user: "{{APPUSER}}"
  notify: Restart Tomcat 

- name: Update Tomcat Context Configuration with Database Details 
  template:
    src: context.xml.j2 
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/context.xml"
  become_user: "{{APPUSER}}" 
  notify: Restart Tomcat 

- name: Download TOmcat Init script 
  get_url:
    url: "{{TOMCAT_INIT_SCRIPT_URL}}"
    dest: /etc/init.d/tomcat 
    mode: u=rwx,g=rx,o=rx 

- name: Reload Systemctl service 
  systemd:
    daemon_reload: yes
  
- name: Start Tomcat Service 
  service:
    name: tomcat 
    state: started
